"use client";
import { useQuery } from "@tanstack/react-query";
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import AppShell from "@/components/layout/AppShell";
import { getBankMetrics } from "@/lib/api/dashboard";
import { getTransactions } from "@/lib/api/transactions";
import { RiskBadge } from "@/components/risk/RiskPieces";
const riskData=[{name:"Low",value:1103,color:"#4ade80"},{name:"Medium",value:61,color:"#facc15"},{name:"High",value:42,color:"#fb923c"},{name:"Critical",value:11,color:"#f87171"}];const scamData=[{name:"Impersonation",value:18},{name:"Account threat",value:11},{name:"Investment",value:7},{name:"Refund",value:5}];
function Chart({data}:{data:{name:string;value:number;color?:string}[]}){return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><XAxis dataKey="name" stroke="#91a7aa" fontSize={11}/><YAxis stroke="#91a7aa" fontSize={11}/><Tooltip contentStyle={{background:'#101a1d',border:'1px solid #2b4548',borderRadius:8}}/><Bar dataKey="value" radius={[4,4,0,0]}>{data.map((d,i)=><Cell key={i} fill={d.color||'#32d8d1'}/>)}</Bar></BarChart></ResponsiveContainer></div>}
export default function Bank(){const metrics=useQuery({queryKey:["bankmetrics"],queryFn:getBankMetrics});const tx=useQuery({queryKey:["transactions"],queryFn:getTransactions});return <AppShell title="Bank Safety Dashboard" description="Monitor high-risk transactions and suspicious recipient activity."><section className="grid metrics">{[["Total Analyzed","analyzed"],["Allowed","allowed"],["Verified","verified"],["Held","held"],["High Risk","highRisk"],["Critical","critical"]].map(([label,key])=><article className="card" key={key}><div className="muted">{label}</div><div className="metric-value">{metrics.data?.[key as keyof typeof metrics.data]??"—"}</div></article>)}</section><section className="grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))",marginTop:28}}><article className="card"><h2>Risk Distribution</h2><Chart data={riskData}/></article><article className="card"><h2>Scam Categories</h2><Chart data={scamData}/></article></section><section className="card section"><h2>Recent High-Risk Transactions</h2><div className="table-wrap"><table className="table"><thead><tr><th>Transaction</th><th>Customer</th><th>Recipient</th><th>Amount</th><th>Risk</th><th>Action</th></tr></thead><tbody>{(tx.data||[]).filter(t=>t.risk.level!=="LOW").map(t=><tr key={t.transaction_id}><td>{t.transaction_id}</td><td>{t.customer}</td><td>{t.recipient_name}</td><td>₹{t.amount.toLocaleString("en-IN")}</td><td><RiskBadge level={t.risk.level}/></td><td>{t.friction.action}</td></tr>)}</tbody></table></div></section><section className="section"><h2 style={{marginBottom:14}}>Suspicious Recipient Clusters</h2><div className="grid" style={{gridTemplateColumns:"repeat(3,1fr)"}}>{["CL-014","CL-022","CL-041"].map((id,i)=><article className="card" key={id}><div className="eyebrow">{id}</div><h3 style={{marginTop:10}}>{[12,8,5][i]} connected customers</h3><p className="muted">{[4,2,1][i]} flags · Elevated recipient risk</p><RiskBadge level={i===0?"CRITICAL":"HIGH"}/></article>)}</div></section></AppShell>}
