"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Activity, CheckCircle2, PauseCircle, ShieldCheck } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import TransactionTable from "@/components/transaction/TransactionTable";
import { getDashboardSummary } from "@/lib/api/dashboard";
import { getTransactions } from "@/lib/api/transactions";
export default function Customer(){const summary=useQuery({queryKey:["summary"],queryFn:getDashboardSummary});const tx=useQuery({queryKey:["transactions"],queryFn:getTransactions});const metrics=[['Payments Analyzed',summary.data?.analyzed,Activity],['Payments Verified',summary.data?.verified,CheckCircle2],['Payments Paused',summary.data?.paused,PauseCircle],['Safety Checks',summary.data?.checks,ShieldCheck]];return <AppShell title="Dashboard" description="Your financial safety overview"><section className="hero card"><div className="eyebrow">Account safety status</div><h2>Good evening</h2><p className="muted">Your payments are protected by RAKSHA.</p><div className="row" style={{marginTop:18}}><span className="status low">● PROTECTION ACTIVE</span><Link href="/customer/send-money" className="btn">Send Money</Link></div></section><section className="grid metrics section">{metrics.map(([name,value,Icon])=>{const I=Icon as typeof Activity;return <article className="card" key={name as string}><div className="row"><span className="muted">{name as string}</span><I className="metric-icon" size={31}/></div><div className="metric-value">{summary.isLoading?"—":value as number}</div><small className="muted">Synthetic demo activity</small></article>})}</section><section className="card section"><div className="row"><div><h2>Recent Activity</h2><p className="muted">Every payment decision is shown in clear language.</p></div><Link href="/customer/transactions" className="btn secondary">View all</Link></div>{tx.isLoading?<p className="muted">Loading recent activity…</p>:tx.isError?<p className="critical">RAKSHA couldn&apos;t load this information.</p>:<TransactionTable transactions={tx.data||[]}/>}</section></AppShell>}
