"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Accessibility, Bell, ChevronRight, LayoutDashboard, Menu, Network, Send, Shield, ShieldAlert, TableProperties, UserRound, X } from "lucide-react";
import { ReactNode, useState } from "react";
const groups: {label: string, items: [string, string, React.ElementType][]}[] = [{label:"CUSTOMER",items:[["Dashboard","/customer",LayoutDashboard],["Send Money","/customer/send-money",Send],["Transactions","/customer/transactions",TableProperties],["Safety Center","/customer/safety",Shield]]},{label:"INVESTIGATION",items:[["Bank Dashboard","/bank",LayoutDashboard],["Fraud Graph","/bank/fraud-graph",Network]]},{label:"DEMO",items:[["Scenarios","/demo",ShieldAlert]]}];
export default function AppShell({title,description,children}:{title:string;description:string;children:ReactNode}) {
  const path=usePathname(); const [open,setOpen]=useState(false); const [large,setLarge]=useState(false); const [panel,setPanel]=useState<"demo"|"notifications"|"profile"|null>(null);
  const toggle=(next:"demo"|"notifications"|"profile")=>setPanel(panel===next?null:next);
  return <div className={`shell ${large?"large-text":""}`}><aside className={`sidebar ${open?"open":""}`}><div className="brand"><span className="brand-mark"><Shield size={20}/></span><div><strong>RAKSHA</strong><div className="muted" style={{fontSize:10}}>Financial Safety Layer</div></div><button className="icon-button mobile-menu" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={18}/></button></div>{groups.map(group=><nav key={group.label} aria-label={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([label,href,Icon])=><Link href={href as string} key={href as string} className={`nav-item ${path===href?"active":""}`} onClick={()=>setOpen(false)}><Icon size={17}/>{label}</Link>)}</nav>)}<div style={{marginTop:"auto"}}><button className="nav-item" onClick={()=>setLarge(!large)} aria-pressed={large}><Accessibility size={17}/>Accessibility</button><div className="nav-item"><span className="demo-dot"/>Demo Mode</div><div className="nav-item"><UserRound size={17}/>Aarav Shah</div></div></aside><main className="content"><header className="topbar"><div className="row" style={{alignItems:"flex-start"}}><button className="icon-button mobile-menu" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={18}/></button><div><h1>{title}</h1><p className="muted" style={{margin:0}}>{description}</p></div></div><div className="top-actions" style={{position:"relative"}}><button className="demo-badge" onClick={()=>toggle("demo")} aria-expanded={panel==="demo"}>DEMO MODE</button><button className="icon-button" onClick={()=>toggle("notifications")} aria-label="Notifications" aria-expanded={panel==="notifications"}><Bell size={17}/></button><button className="icon-button" onClick={()=>setLarge(!large)} aria-label="Toggle large text" aria-pressed={large}><Accessibility size={17}/></button><button className="avatar" onClick={()=>toggle("profile")} aria-label="Aarav Shah profile menu" aria-expanded={panel==="profile"}>AS</button>{panel&&<TopbarPanel panel={panel} close={()=>setPanel(null)}/>}</div></header>{children}</main></div>
}

function TopbarPanel({panel,close}:{panel:"demo"|"notifications"|"profile";close:()=>void}) { return <section className="card" role="dialog" aria-label={`${panel} panel`} style={{position:"absolute",right:0,top:48,width:285,zIndex:30,boxShadow:"0 16px 40px rgba(0,0,0,.45)"}}>{panel==="demo"&&<><div className="eyebrow">Demo Mode Active</div><h3 style={{marginTop:8}}>Synthetic data only</h3><p className="muted">Every recipient, payment, and safety decision is a deterministic demo scenario.</p><Link href="/demo" className="btn" onClick={close}>Open scenarios <ChevronRight size={16}/></Link></>}{panel==="notifications"&&<><div className="eyebrow">Notifications</div><h3 style={{marginTop:8}}>1 payment safety update</h3><p className="muted">A high-risk payment was paused for review. No money was sent.</p><button className="btn secondary" onClick={close}>Mark as read</button></>}{panel==="profile"&&<><div className="eyebrow">Profile</div><h3 style={{marginTop:8}}>Aarav Shah</h3><p className="muted">Demo customer · Protection active</p><Link href="/customer/safety" className="btn secondary" onClick={close}>Open Safety Center</Link></>}</section> }
