"use client";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import AppShell from "@/components/layout/AppShell";
import TransactionTable from "@/components/transaction/TransactionTable";
import { getTransactions } from "@/lib/api/transactions";
import { Transaction } from "@/types";
import { FrictionCard, IntelligenceCard, RiskCard } from "@/components/risk/RiskPieces";
export default function Transactions(){const query=useQuery({queryKey:["transactions"],queryFn:getTransactions});const [search,setSearch]=useState("");const [risk,setRisk]=useState("ALL");const [selected,setSelected]=useState<Transaction>();const rows=useMemo(()=> (query.data||[]).filter(t=>(risk==="ALL"||t.risk.level===risk)&&`${t.transaction_id}${t.recipient_name}`.toLowerCase().includes(search.toLowerCase())),[query.data,risk,search]);return <AppShell title="Transactions" description="Review payment decisions made by RAKSHA."><section className="card"><div className="row" style={{justifyContent:"flex-start",flexWrap:"wrap"}}><input aria-label="Search transactions" placeholder="Search recipient or ID" value={search} onChange={e=>setSearch(e.target.value)} style={{background:'#071012',border:'1px solid #284044',color:'white',padding:10,borderRadius:8}}/><select aria-label="Filter by risk" value={risk} onChange={e=>setRisk(e.target.value)} style={{background:'#071012',border:'1px solid #284044',color:'white',padding:10,borderRadius:8}}><option>ALL</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div>{query.isLoading?<p className="muted">Loading transactions…</p>:<TransactionTable transactions={rows} onSelect={setSelected}/>}</section>{selected&&<section className="card section"><div className="row"><div><div className="eyebrow">Transaction detail</div><h2>{selected.transaction_id} · {selected.recipient_name}</h2></div><button className="btn ghost" onClick={()=>setSelected(undefined)}>Close</button></div><div className="grid analysis-grid" style={{marginTop:18}}><div className="grid"><IntelligenceCard title="Behavior" question="Customer behavior signals" data={selected.behavior}/><IntelligenceCard title="Recipient" question="Recipient signals" data={selected.recipient}/><IntelligenceCard title="Intent" question="Payment intent signals" data={selected.intent}/></div><div className="grid"><RiskCard risk={selected.risk}/><FrictionCard data={selected.friction}/></div></div></section>}</AppShell>}
