import { TransactionAnalysisResponse } from "@/types";

const timestamp="Today, 6:42 PM";
export const mockRiskScenarios:Record<"LOW"|"MEDIUM"|"HIGH"|"CRITICAL",TransactionAnalysisResponse>={
  LOW:{transaction_id:"TX1001",recipient_name:"FreshMart Grocery",amount:1000,reason:"Grocery purchase",timestamp,behavior:{score:12,signals:["TYPICAL_AMOUNT","NORMAL_PAYMENT_PATTERN"]},recipient:{score:8,signals:["FAMILIAR_RECIPIENT","ESTABLISHED_MERCHANT"]},intent:{score:4,category:"MERCHANT_PURCHASE",signals:["CLEAR_PURCHASE_REASON"]},risk:{score:12,level:"LOW"},friction:{action:"ALLOW",title:"Payment looks normal",message:"This payment matches your usual activity."}},
  MEDIUM:{transaction_id:"TX1002",recipient_name:"Priya Sharma",amount:12000,reason:"Personal transfer",timestamp,behavior:{score:48,signals:["UNUSUAL_AMOUNT"]},recipient:{score:44,signals:["LESS_FREQUENT_RECIPIENT"]},intent:{score:32,category:"PERSONAL_TRANSFER",signals:["NEW_PAYMENT_CONTEXT"]},risk:{score:48,level:"MEDIUM"},friction:{action:"VERIFY",title:"Please verify this payment",message:"This payment is different from your usual activity."}},
  HIGH:{transaction_id:"TX1003",recipient_name:"Ravi Kumar",amount:25000,reason:"Personal transfer",timestamp,behavior:{score:78,signals:["UNUSUAL_AMOUNT","UNUSUAL_TIME"]},recipient:{score:72,signals:["NEW_RECIPIENT"]},intent:{score:65,category:"PERSONAL_TRANSFER",signals:["UNUSUAL_REQUEST"]},risk:{score:78,level:"HIGH"},friction:{action:"STRONG_VERIFY",title:"Review this payment carefully",message:"This payment has several unusual signals."}},
  CRITICAL:{transaction_id:"TX1004",recipient_name:"Rahul Sharma",amount:45000,reason:"Bank verification",timestamp,behavior:{score:88,signals:["UNUSUAL_AMOUNT"]},recipient:{score:82,signals:["NEW_RECIPIENT"]},intent:{score:96,category:"BANK_IMPERSONATION",signals:["URGENT_REQUEST","AUTHORITY_IMPERSONATION"]},risk:{score:96,level:"CRITICAL"},friction:{action:"HOLD",title:"Potential scam detected",message:"This payment shows signs of possible social engineering."}}
};
